### PR TITLE
Add basic downgrade release

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by eshimischi** [comment]
That's what you meant, i see!

**Comment by eshimischi** [comment]
Rector is really helpful tool, was and is impressed by it since the day 1. Don't see any issues here, will you merge this soon?

**Comment by eshimischi** [comment]
Good job, thanks!

**Comment by TomasVotruba** [comment]
You're welcome :+1: 

Still working on it, better check tomorrow same time.

**Pull request merged**
